{{- if .Values.ingress.backend.enabled -}}
{{- $fullName := include "backend.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $ingressClass := index .Values.ingress.backend.className -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-{{ $fullName }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    konghq.com/plugins: {{ $fullName }}-cors
  {{- with .Values.ingress.backend.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $ingressClass }}
  {{- if .Values.ingress.backend.tls }}
  tls:
    {{- range .Values.ingress.backend.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.backend.host }}
      http:
        paths:
          - path: "/"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          - path: "/api/v1/public"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
