{{- if .Values.ingress.backend.enabled -}}
{{- $fullName := include "backend.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $ingressClass := index .Values.ingress.backend.annotations "kubernetes.io/ingress.class" -}}
{{- if and .Values.ingress.backend.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.backend.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.backend.annotations "kubernetes.io/ingress.class" .Values.ingress.backend.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: private-{{ $fullName }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    konghq.com/plugins: {{ $fullName }}-cors, {{ $fullName }}-validate-auth-server-token
  {{- with .Values.ingress.backend.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressClass (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $ingressClass }}
  {{- end }}
  {{- if .Values.ingress.backend.tls }}
  tls:
    {{- range .Values.ingress.backend.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.backend.host }}
      http:
        paths:
          {{- range .Values.ingress.private.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
{{- end }}
