{{- if .Values.ingress.backend.enabled -}}
{{- $fullName := include "backend.fullname" . -}}
{{- $corsPluginName := printf "%s-%s" $fullName "cors" }}
{{- $validateAuthServerTokenPluginName := printf "%s-%s" $fullName "validate-auth-server-token" }}
{{- $namespace := .Release.Namespace -}}
apiVersion: configuration.konghq.com/v1
config:
  origins:
  - '*'
kind: KongPlugin
metadata:
  name: {{ trunc 63 $corsPluginName }}
plugin: cors
---
apiVersion: configuration.konghq.com/v1
config:
  auth_method: client_secret_basic
  auth_response_headers_to_forward:
  - sub
  - current-address
  client_id: {{ .Values.ingress.private.oauth.client_id }}
  client_secret: {{ .Values.ingress.private.oauth.client_secret }}
  token_introspect_url: {{ printf "http://%s.%s/%s" "auth" $namespace "oauth/token/introspect" | quote }}
kind: KongPlugin
metadata:
  name: {{ trunc 63 $validateAuthServerTokenPluginName }}
plugin: oauth2-token-introspection-request
{{- end }}