apiVersion: v1
data:
  web3-provider: {{ default "" .Values.config.web3Provider | quote }}
  alchemy-api-key: {{ default "" .Values.config.alchemyApiKey | quote }}
  alchemy-http-endpoint: {{ default "" .Values.config.alchemyHttpEndpoint | quote }}
  alchemy-ws-endpoint: {{ default "" .Values.config.alchemyWsEndpoint | quote }}
  aws-access-key-id: {{ default "" .Values.config.awsAccessKeyId | quote }}
  aws-secret-access-key: {{ default "" .Values.config.awsSecretAccessKey | quote }}
  aws-region: {{ default "" .Values.config.awsRegion  | quote }}
  amb-http-endpoint: {{ default "" .Values.config.ambHttpEndpoint | quote }}
  amb-ws-endpoint: {{ default "" .Values.config.ambWsEndpoint | quote }}
  chain-id: {{ default "" .Values.config.chainId | quote }}
  order-contract-address: {{ default "" .Values.config.orderContractAddress | quote }}
  exchange-contract-address: {{ default "" .Values.config.exchangeContractAddress | quote }}
  new-block-headers-queue-url: {{ default "" .Values.config.newBlockHeadersQueueUrl | quote }}
  nft-transfer-event-queue-url: {{ default "" .Values.config.nftTransferEventQueueUrl | quote }}
  order-fill-changed-event-queue-url: {{ default "" .Values.config.orderFillChangedEventQueueUrl | quote }}
  orders-matched-event-queue-url: {{ default "" .Values.config.ordersMatchedEventQueueUrl | quote }}
  ownership-transferred-event-queue-url: {{ default "" .Values.config.ownershipTransferredEventQueueUrl | quote }}
  exchange-event-queue-url: {{ default "" .Values.config.exchangeEventQueueUrl | quote }}
  db-engine: {{ default "" .Values.config.dbEngine | quote }}
  db-port: {{ default "" .Values.config.dbPort | quote }}
  db-database: {{ default "" .Values.config.dbDatabase | quote }}
  db-password: {{ default "" .Values.config.dbPassword | quote }}
  db-host: {{ default "" .Values.config.dbHost | quote }}
  db-user: {{ default "" .Values.config.dbUser | quote }}

kind: ConfigMap
metadata:
  name: {{ include "event-listener.fullname" . }}

