apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: api-endpoint
                  name: {{ include "frontend.fullname" . }}
            - name: AUTH_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: auth-api-endpoint
                  name: {{ include "frontend.fullname" . }}
            - name: ETHER_CHAIN
              valueFrom:
                configMapKeyRef:
                  key: ether-chain
                  name: {{ include "frontend.fullname" . }}
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  key: sentry-dsn
                  name: {{ include "frontend.fullname" . }}
            - name: USDC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: usdc-address
                  name: {{ include "frontend.fullname" . }}
            - name: WETH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: weth-address
                  name: {{ include "frontend.fullname" . }}
            - name: CDN_HOST_URL
              valueFrom:
                configMapKeyRef:
                  key: cdn-host-url
                  name: {{ include "frontend.fullname" . }}
            - name: S3_HOST_URL
              valueFrom:
                configMapKeyRef:
                  key: s3-host-url
                  name: {{ include "frontend.fullname" . }}
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: base-url
                  name: {{ include "frontend.fullname" . }}
            - name: GTM_ID
              valueFrom:
                configMapKeyRef:
                  key: gtm-id
            - name: OAUTH_REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  key: oauth-refresh-token-expires-in
                  name: {{ include "frontend.fullname" . }}
            - name: USE_REDUX_LOGGER
              valueFrom:
                configMapKeyRef:
                  key: use-redux-logger
                  name: {{ include "frontend.fullname" . }}
            - name: GTM_ID
              valueFrom:
                configMapKeyRef:
                  key: gtm-id
                  name: {{ include "frontend.fullname" . }}

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
