apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}
data:
  oauth2-token-expires-in-password: {{ default "" .Values.config.oauth2TokenExpiresInPassword | quote }}
  oauth2-refresh-token-expires-in: {{ default "" .Values.config.oauth2RefreshTokenExpiresIn | quote }}
  aws-region: {{ default "" .Values.config.awsRegion | quote }}
  aws-access-key: {{ default "" .Values.config.awsAccessKey | quote }}
  aws-secret-key: {{ default "" .Values.config.awsSecretKey | quote }}
  new-account-report-queue-url: {{ default "" .Values.config.newAccountReportQueueUrl | quote }}
  nonce-template: {{ default "" .Values.config.nonceTemplate | b64enc | quote }}
  tos-url: {{ default "" .Values.config.tosUrl | quote }}
  identity-danal-api-base: {{ default "" .Values.config.identityDanalApiBase | quote }}
  identity-danal-cpid: {{ default "" .Values.config.identityDanalCPID | quote }}
  identity-danal-cppwd: {{ default "" .Values.config.identityDanalCPPWD | quote }}
  identity-danal-target-url: {{ default "" .Values.config.identityDanalTargetUrl | quote }}
  identity-oauth-client-id: {{ default "" .Values.config.identityOauthClientId | quote }}
  identity-redirect-url: {{ default "" .Values.config.identityRedirectUrl | quote }}

