apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth.fullname" . }}
data:
  oauth2-token-expires-in-password: {{ default "" .Values.config.oauth2TokenExpiresInPassword | quote }}
  oauth2-refresh-token-expires-in: {{ default "" .Values.config.oauth2RefreshTokenExpiresIn | quote }}
  aws-region: {{ default "" .Values.config.awsRegion | quote }}
  aws-access-key: {{ default "" .Values.config.awsAccessKey | quote }}
  aws-secret-key: {{ default "" .Values.config.awsSecretKey | quote }}
  new-account-report-queue-url: {{ default "" .Values.config.newAccountReportQueueUrl | quote }}

