apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth.fullname" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AUTHLIB_INSECURE_TRANSPORT
              value: "1"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: {{ include "auth.fullname" . }}-database
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  key: engine
                  name: {{ include "auth.fullname" . }}-database
            - name: OAUTH2_TOKEN_EXPIRES_IN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: oauth2-token-expires-in-password
                  name: {{ include "auth.fullname" . }}
            - name: OAUTH2_REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  key: oauth2-refresh-token-expires-in
                  name: {{ include "auth.fullname" . }}
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  key: aws-region
                  name: {{ include "auth.fullname" . }}
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: aws-access-key
                  name: {{ include "auth.fullname" . }}
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: aws-secret-key
                  name: {{ include "auth.fullname" . }}
            - name: NEW_ACCOUNT_REPORT_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: new-account-report-queue-url
                  name: {{ include "auth.fullname" . }}
            - name: NONCE_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  key: nonce-template
                  name: {{ include "auth.fullname" . }}
            - name: TOS_URL
              valueFrom:
                configMapKeyRef:
                  key: tos-url
                  name: {{ include "auth.fullname" . }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
