apiVersion: v1
data:
  host: {{ default "" .Values.database.host | b64enc | quote }}
  user: {{ default "" .Values.database.user | b64enc | quote }}
  port: {{ default "" .Values.database.port | b64enc | quote }}
  password: {{ default "" .Values.database.password | b64enc | quote }}
  database: {{ default "" .Values.database.database | b64enc | quote }}
  engine: {{ default "" .Values.database.engine | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "auth.fullname" . }}-database
type: Opaque

