apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment.fullname" . }}-hecto
type: Opaque
data:
  hash_secret: {{ default "" .Values.secret.hecto.hash_secret | b64enc | quote }}
  mid: {{ default "" .Values.secret.hecto.mid | b64enc | quote }}
  net_pay_cancle: {{ default "" .Values.secret.hecto.net_pay_cancle | b64enc | quote }}
  payment_info: {{ default "" .Values.secret.hecto.payment_info | b64enc | quote }}
  pay_cancle: {{ default "" .Values.secret.hecto.pay_cancle | b64enc | quote }}
  pay_approve: {{ default "" .Values.secret.hecto.pay_approve | b64enc | quote }}
  tr_info: {{ default "" .Values.secret.hecto.tr_info | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment.fullname" . }}-database
type: Opaque
data:
  host: {{ default "" .Values.secret.database.host | b64enc | quote }}
  engine: {{ default "" .Values.secret.database.engine | b64enc | quote }}
  database: {{ default "" .Values.secret.database.database | b64enc | quote }}
  password: {{ default "" .Values.secret.database.password | b64enc | quote }}
  port: {{ default "" .Values.secret.database.port | b64enc | quote }}
  user: {{ default "" .Values.secret.database.user | b64enc | quote }}
  pool_size: {{ default "" .Values.secret.database.pool_size | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment.fullname" . }}-alchemy
type: Opaque
data:
  api_key: {{ default "" .Values.secret.alchemy.api_key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment.fullname" . }}-aws-credentials
type: Opaque
data:
  region: {{ default "" .Values.secret.aws.region | b64enc | quote }}
  access_key: {{ default "" .Values.secret.aws.access_key | b64enc | quote }}
  secret_key: {{ default "" .Values.secret.aws.secret_key | b64enc | quote }}