apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment.fullname" . }}-hecto
type: Opaque
data:
  hash_secret: {{ default "" .Values.secret.hecto.hash_secret | b64enc | quote }}
  mid: {{ default "" .Values.secret.hecto.mid | b64enc | quote }}
  net_pay_cancle: {{ default "" .Values.secret.hecto.net_pay_cancle | b64enc | quote }}
  payment_info: {{ default "" .Values.secret.hecto.payment_info | b64enc | quote }}
  pay_cancle: {{ default "" .Values.secret.hecto.pay_cancle | b64enc | quote }}
  pay_approve: {{ default "" .Values.secret.hecto.pay_approve | b64enc | quote }}
  tr_info: {{ default "" .Values.secret.hecto.tr_info | b64enc | quote }}
  backend_callback_url: {{ default "" .Values.secret.hecto.backend_callback_url | b64enc | quote }}
  frontend_callback_url: {{ default "" .Values.secret.hecto.frontend_callback_url | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment.fullname" . }}-database-config
type: Opaque
data:
  host: {{ default "" .Values.secret.database.host | b64enc | quote }}
  engine: {{ default "" .Values.secret.database.engine | b64enc | quote }}
  database: {{ default "" .Values.secret.database.database | b64enc | quote }}
  password: {{ default "" .Values.secret.database.password | b64enc | quote }}
  port: {{ default "" .Values.secret.database.port | b64enc | quote }}
  user: {{ default "" .Values.secret.database.user | b64enc | quote }}