apiVersion: v1
kind: Secret
metadata:
  name: {{ include "account.fullname" . }}-database
data:
  engine: {{ default "" .Values.config.database.engine | b64enc |quote }}
  host: {{ default "" .Values.config.database.host | b64enc |quote }}
  port: {{ default "" .Values.config.database.port | b64enc |quote }}
  database: {{ default "" .Values.config.database.database | b64enc |quote }}
  password: {{ default "" .Values.config.database.password | b64enc |quote }}
  user: {{ default "" .Values.config.database.user | b64enc |quote }}
