apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inapp.fullname" . }}
  labels: 
    {{- include "inapp.labels" . | nindent 4 }}
data:
  authBaseUrl: {{ default "" .Values.config.oauth.authBaseUrl | b64enc | quote }}
  clientId: {{ default "" .Values.config.oauth.clientId | b64enc | quote }}
  clientSecret: {{ default "" .Values.config.oauth.clientSecret | b64enc | quote }}
