apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
data:
  ethreum_network: {{ default "" .Values.config.backend.ethreum_network | quote }}
  marketplace_nft_address: {{ default "" .Values.config.backend.marketplace_nft_address | quote }}
  network_provider: {{ default "" .Values.config.backend.network_provider | quote }}
  event_listener_host: {{ default "" .Values.config.event_listener_host | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-aws-queue
data:
  collectionQueue: {{ default "" .Values.config.aws.queue.collectionQueue | quote }}
  allItemQueue: {{ default "" .Values.config.aws.queue.allItemQueue | quote }}
  itemQueue: {{ default "" .Values.config.aws.queue.itemQueue | quote }}
  changeItemOwnerQueue: {{ default "" .Values.config.aws.queue.changeItemOwnerQueue | quote }}
  refreshItemMetaQueue: {{ default "" .Values.config.aws.queue.refreshItemMetaQueue | quote }}
  orderFillChangedQueue: {{ default "" .Values.config.aws.queue.orderFillChangedQueue | quote }}
  orderFillChangedQueueUrl: {{ default "" .Values.config.aws.queue.orderFillChangedQueueUrl | quote }}
  ordersMatchedQueue: {{ default "" .Values.config.aws.queue.ordersMatchedQueue | quote }}
  ordersMatchedQueueUrl: {{ default "" .Values.config.aws.queue.ordersMatchedQueueUrl | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-contract
data:
  marketplace: {{ default "" .Values.config.contract_address.market | quote }}
  weth: {{ default "" .Values.config.contract_address.weth | quote }}
  usdc: {{ default "" .Values.config.contract_address.usdc | quote }}