apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
data:
  ethreum_network: {{ default "" .Values.config.backend.ethreum_network | quote }}
  marketplace_nft_address: {{ default "" .Values.config.backend.marketplace_nft_address | quote }}
  network_provider: {{ default "" .Values.config.backend.network_provider | quote }}
  event_listener_host: {{ default "" .Values.config.event_listener_host | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-aws-queue
data:
  collectionQueueName: {{ default "" .Values.config.aws.queue.collectionQueueName | quote }}
  collectionQueueUrl: {{ default "" .Values.config.aws.queue.collectionQueueUrl | quote }}
  allItemQueueName: {{ default "" .Values.config.aws.queue.allItemQueueName | quote }}
  allItemQueueUrl: {{ default "" .Values.config.aws.queue.allItemQueueUrl | quote }}
  itemQueueName: {{ default "" .Values.config.aws.queue.itemQueueName | quote }}
  itemQueueUrl: {{ default "" .Values.config.aws.queue.itemQueueUrl | quote }}
  changeItemOwnerQueueName: {{ default "" .Values.config.aws.queue.changeItemOwnerQueueName | quote }}
  changeItemOwnerQueueUrl: {{ default "" .Values.config.aws.queue.changeItemOwnerQueueUrl | quote }}
  refreshItemMetaQueueName: {{ default "" .Values.config.aws.queue.refreshItemMetaQueueName | quote }}
  refreshItemMetaQueueUrl: {{ default "" .Values.config.aws.queue.refreshItemMetaQueueUrl | quote }}
  orderFillChangedQueueName: {{ default "" .Values.config.aws.queue.orderFillChangedQueueName | quote }}
  orderFillChangedQueueUrl: {{ default "" .Values.config.aws.queue.orderFillChangedQueueUrl | quote }}
  ordersMatchedQueueName: {{ default "" .Values.config.aws.queue.ordersMatchedQueueName | quote }}
  ordersMatchedQueueUrl: {{ default "" .Values.config.aws.queue.ordersMatchedQueueUrl | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-contract
data:
  marketplace: {{ default "" .Values.config.contract_address.market | quote }}
  weth: {{ default "" .Values.config.contract_address.weth | quote }}
  usdc: {{ default "" .Values.config.contract_address.usdc | quote }}