apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ETHEREUM_NETWORK
              valueFrom:
                configMapKeyRef:
                  key: ethreum_network
                  name: {{ include "backend.fullname" . }}-config
            - name: MARKETPLACE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: marketplace
                  name: {{ include "backend.fullname" . }}-contract
            - name: MARKETPLACE_NFT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: marketplace_nft_address
                  name: {{ include "backend.fullname" . }}-config
            - name: NETWORK_PROVIDER
              valueFrom:
                configMapKeyRef:
                  key: network_provider
                  name: {{ include "backend.fullname" . }}-config
            - name: ALCHEMY_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "backend.fullname" . }}-alchemy-secret
            - name: ALCHEMY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: {{ include "backend.fullname" . }}-alchemy-secret
            - name: OPENSEA_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: {{ include "backend.fullname" . }}-opensea-secret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: {{ include "backend.fullname" . }}-database-config
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ include "backend.fullname" . }}-database-config
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "backend.fullname" . }}-database-config
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: {{ include "backend.fullname" . }}-database-config
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: {{ include "backend.fullname" . }}-database-config
            - name: DB_ENGINE
              valueFrom:
                secretKeyRef:
                  key: engine
                  name: {{ include "backend.fullname" . }}-database-config
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: region
                  name: {{ include "backend.fullname" . }}-aws-credentials
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: access_key
                  name: {{ include "backend.fullname" . }}-aws-credentials
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret_key
                  name: {{ include "backend.fullname" . }}-aws-credentials
            - name: WETH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: weth
                  name: {{ include "backend.fullname" . }}-contract
            - name: USDC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: usdc
                  name: {{ include "backend.fullname" . }}-contract
            - name: QUEUE_COLLECTION
              valueFrom:
                configMapKeyRef:
                  key: collectionQueue
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: QUEUE_ALL_ITEM
              valueFrom:
                configMapKeyRef:
                  key: allItemQueue
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: QUEUE_ITEM
              valueFrom:
                configMapKeyRef:
                  key: itemQueue
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: QUEUE_ITEM_TX
              valueFrom:
                configMapKeyRef:
                  key: changeItemOwnerQueue
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: QUEUE_REFRESH_ITEM_META
              valueFrom:
                configMapKeyRef:
                  key: refreshItemMetaQueue
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: ORDER_FILL_CHANGED_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: orderFillChangedQueue
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: ORDER_FILL_CHANGED_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: orderFillChangedQueueUrl
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: ORDERS_MATCHED_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: ordersMatchedQueue
                  name: {{ include "backend.fullname" . }}-aws-queue
            - name: ORDERS_MATCHED_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  key: ordersMatchedQueueUrl
                  name: {{ include "backend.fullname" . }}-aws-queue
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
